[package]
name = "saikoro"
version = "2.0.0-dev"
authors = ["Morgan Bauer"]
homepage = "https://jolkert.dev/saikoro"
edition = "2024"
description = "Parser and evaluator for doing math with dice notation expressions"
repository = "https://github.com/Jolkert/saikoro"
license = "MIT OR Apache-2.0"
keywords = ["dice", "parser", "math"]
categories = ["mathematics", "parser-implementations"]
exclude = ["bacon.toml", ".vscode/", "CHANGELOG.md"]

[features]
# the default feaures *should* be empty. we put them on full
# because its the least painful way to make sure rust-analyzer
# checks all the code instead of just parts of it :)
# -morgan 2025-06-08
default = ["full"]
stats = []
serde = ["dep:serde"]
full = ["stats", "serde"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy-regex = "3.1.0"
lazy_static = "1.4.0"
rand = "0.9.1"
regex = "1.9.4"
serde = { version = "1.0.219", features = ["derive"],  optional = true }
thiserror = "1.0.51"

[dev-dependencies]
ron = "0.10.1"

[lints.clippy]
pedantic = "warn"
nursery = "warn"
empty_structs_with_brackets = "warn"
if_then_some_else_none = "warn"
same_name_method = "warn"
lossy_float_literal = "warn"

missing_const_for_fn = {level = "allow", priority = 1}
cast_possible_truncation = {level = "allow", priority = 1}
missing-errors-doc = {level = "allow", priority = 1}
module_name_repetitions = {level = "allow", priority = 1}
must-use-candidate = {level = "allow", priority = 1}
trivial-regex = {level = "allow", priority = 1}
neg_cmp_op_on_partial_ord = {level = "allow", priority = 1}
match-wildcard-for-single-variants = {level = "allow", priority = 1}

